// <auto-generated />
using System;
using Hackathon.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hackathon.Infra.Data.Migrations
{
    [DbContext(typeof(SQLServerContext))]
<<<<<<<< HEAD:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230313231953_SQLite.Designer.cs
    [Migration("20230313231953_SQLite")]
    partial class SQLite
========
    [Migration("20230312213522_Alterando-Relato")]
    partial class AlterandoRelato
>>>>>>>> main:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230312213522_Alterando-Relato.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Hackathon.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Iluminação Pública"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Segurança Pública"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Transporte Público"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Vias Públicas"
                        });
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Relato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
<<<<<<<< HEAD:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230313231953_SQLite.Designer.cs
                        .HasColumnType("TEXT");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("TEXT");
========
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
>>>>>>>> main:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230312213522_Alterando-Relato.Designer.cs

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContadorLikes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
<<<<<<<< HEAD:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230313231953_SQLite.Designer.cs
                        .HasColumnType("TEXT");
========
                        .HasColumnType("nvarchar(max)");
>>>>>>>> main:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230312213522_Alterando-Relato.Designer.cs

                    b.Property<string>("Relatorio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rua")
                        .IsRequired()
<<<<<<<< HEAD:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230313231953_SQLite.Designer.cs
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");
========
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");
>>>>>>>> main:SlnHackathon/src/Hackathon.Infra.Data/Migrations/20230312213522_Alterando-Relato.Designer.cs

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Relatos");
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anonimo@gmail.com",
                            Nome = "Anônimo",
                            Senha = "Anonimo"
                        },
                        new
                        {
                            Id = 2,
                            Email = "joao@gmail.com",
                            Nome = "João",
                            Senha = "Joao",
                            Telefone = "(47) 991456-5645"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@gmail.com",
                            Nome = "Maria",
                            Senha = "Maria",
                            Telefone = "(47) 99115-5712"
                        },
                        new
                        {
                            Id = 4,
                            Email = "felipe@gmail.com",
                            Nome = "Felipe",
                            Senha = "Felipe",
                            Telefone = "(47) 99748-9632"
                        });
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Relato", b =>
                {
                    b.HasOne("Hackathon.Domain.Entities.Categoria", "Categoria")
                        .WithMany("RelatosList")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackathon.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RelatosList")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("RelatosList");
                });

            modelBuilder.Entity("Hackathon.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RelatosList");
                });
#pragma warning restore 612, 618
        }
    }
}
